---
# Ubuntu
- hosts: all
  become: yes

  tasks:
  - name: Install Docker
    yum: name=docker state=present

  - name: Enable Docker
    service: name=docker enabled=yes state=started

  - name: Install Kubernetes repository
    shell:
      cmd: |
        cat <<EOF > /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        EOF

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Install Kubernetes repo
    yum_repository:
      name: kubernetes
      description: Kubernetes repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      repo_gpgcheck: 1
      gpgcheck: 1
      enabled: 1
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install GPG keys from Google 1
    rpm_key:
      state: present
      key: https://packages.cloud.google.com/yum/doc/yum-key.gpg

  - name: Install GPG keys from Google 2
    rpm_key:
      state: present
      key: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: Install kubelet kubeadm kubectl
    yum: name={{item}} state=present
    with_items:
      - kubelet
      - kubeadm
      - kubectl

  - name: Enable Kubelet
    service: name=kubelet enabled=yes state=started